spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: xiangjiaxin
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
    servlet:
      content-type: text/html;charset=utf-8

mybatis:
  mapper-locations: classpath*:mappers/**/*.xml

redis:
  port: 6379
  database: DB1
  host: 127.0.0.1

net:
  seehope:
    springboot:
      showapi:
        covid_19API:
          appid: 896730
          appsecret: 57da4771b57c411a98c761bdbe10b544
          url: http://route.showapi.com/2217-2

